version: '3.8'

services:
  tekmetric-automation:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tekmetric-hourly-automation
    restart: unless-stopped
    
    # Use .env file automatically
    env_file:
      - .env
    
    # Additional environment variables for Docker
    environment:
      - TZ=America/Phoenix
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
    
    # Volume mounts for persistent data (like your daily version)
    volumes:
      - ./Financial Reports:/app/Financial Reports
      - ./RO Reports:/app/RO Reports
      - ./logs:/app/logs
    
    # Resource limits for Azure
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/app.py') else 1)"]
      interval: 300s
      timeout: 30s
      retries: 3
      start_period: 60s
    
    # Network configuration
    networks:
      - automation-network
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

# Networks
networks:
  automation-network:
    driver: bridge
