version: '3.8'

services:
  tekmetric-automation:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tekmetric-automation
    restart: unless-stopped
    
    # Use .env file automatically
    env_file:
      - .env
    
    # Additional environment variables for Docker
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    
    # Volume mounts for persistent data
    volumes:
      - ./Financial Reports:/app/Financial Reports
      - ./RO Reports:/app/RO Reports
      - ./logs:/app/logs
      - playwright-cache:/ms-playwright
    
    # Resource limits for Azure
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import pymssql; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Network configuration
    networks:
      - automation-network
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

# Named volumes
volumes:
  playwright-cache:
    driver: local

# Networks
networks:
  automation-network:
    driver: bridge
