version: '3.8'

services:
  tekmetric-hourly-automation:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gemba-tekmetric-hourly-automation
    restart: unless-stopped
    environment:
      - TZ=America/Phoenix
      - PYTHONUNBUFFERED=1
      # SECURITY FIX: Remove default values - these MUST be set in .env file
      - TEKMETRIC_EMAIL=${TEKMETRIC_EMAIL}
      - TEKMETRIC_PASSWORD=${TEKMETRIC_PASSWORD}
      - SQL_SERVER=${SQL_SERVER:-gembadb.database.windows.net}
      - SQL_DATABASE=${SQL_DATABASE:-gemba}
      - SQL_USERNAME=${SQL_USERNAME:-gembauser}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_PORT=${SQL_PORT:-1433}
    volumes:
      - ./Financial Reports:/app/Financial Reports
      - ./RO Reports:/app/RO Reports
      - ./logs:/app/logs
    networks:
      - tekmetric-hourly-network
    # Enhanced health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/app.py') else 1)"]
      interval: 300s
      timeout: 30s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    # Resource limits for Azure server
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

networks:
  tekmetric-hourly-network:
    driver: bridge